version: '3'
services:
  dbserver:
    image: youruser/dbserver
    ports:
      - "27017:27017"
    networks:
      - outside

  webserver:
    image: youruser/webserver
    ports:
      - "5000:5000"
    networks:
        - outside

networks:
  outside:
    external:
      name: minitwit-network
